### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by Goose-Of-War** [Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070#1]
Hi. First off, great work with the task. There are some things which you can optimize in this, but considering you have Midsems, we can discuss it later. Meanwhile, there are some things which need to be changed though.

First off, your README is incomplete with the details. Unlike the other teams, we are not taking Google Form submissions, the README serves as our means to get the applicant information. Your README should contain the following details:
- Name and Roll Number
- Discord Username
- MyAnimeList/Anilist Username
- A brief introduction
- Contact details

Kindly fill in the following details at your earliest and reply to this issue. If you are open to optimizing your front end, do mention it. I'll make some issues which highlight what can be improved

**Comment by VikasRavidas** [comment]
NAME -VIKAS RAVIDAS
ROLL NO-22MA10070.
As mid sem is over please help me to optimize the front end and highlight
the issues.

**Comment by Goose-Of-War** [comment]
Hey. Would appreciate if you filled all the details mentioned in the list before we close this issue. Meanwhile, I'll highlight the other things you can work on in other issues

**Comment by VikasRavidas** [comment]
Almost Done. Please mention if I have left anything .
