### ISSUE TITLE
Profile in Navbar going outside bounds

### ISSUE THREAD

**Issue by Goose-Of-War** [Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070#2]
![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/4508a147-b8d3-4c3c-bb72-17a89a75d42c)

From the screenshot, you can see that the profile text is going outside the navbar. Fixing that one itself can improve the navbar looks by a decent amount. I would preferably suggest that you scale up the other things on the navbar rather than shrinking the profile.

**Comment by VikasRavidas** [comment]
Please check the commits I have made and let me know any other changes in
the navbar that I will have to make.

**Comment by Goose-Of-War** [comment]
![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/c9f4ccb5-d27a-4e27-8f16-004190bd09b0)

This is the current navbar which I am seeing. There are two things which you can do.
1. Add some spacing on the top and bottom the profile. It almost feels like the profile is congested in the navbar. Padding makes a wonderful difference in making things look well accomodated.
2. Add some space between the theme toggle div and the profile. As opposed to the space between "Home", "Movies", "Series" etc, this feels really squished together.

**Comment by VikasRavidas** [comment]
Please check once the commits I have made and let me know the issues.

**Comment by Goose-Of-War** [comment]
![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/06d49cda-691c-4e4c-8f8b-2e34c04ac61e)
Somehow it became a bit worse 💀
