### ISSUE TITLE
Theme toggle optimization

### ISSUE THREAD

**Issue by Goose-Of-War** [Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070#3]
First off, hats off for thinking of going dual themes, i.e., dark and light themes. However, the interface you have used is kinda... painful to use. 

![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/7ba02961-abdf-46d9-8431-e174caa1372e)

I saw the source code as well, and I can see that the trigger works only when you click the circle(`.toggle-ball`) which is annoying when you have a div that is thrice the size of the ball and it as a whole represents theme toggling.

Therefore, what I want to suggest is that you make it such that clicking on anywhere on the div (as in both `.toggle` and `.toggle-ball`) would cause a theme change.

Also, waiting 1s for transition is too long considering the average attention span of people. I would recommend 0.3s as a personal preference for transition times.

**Comment by Goose-Of-War** [comment]
The time taken is improved, but there is another issue

![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/972d834f-f9d7-41a4-a802-eff48bf1ca2e)

The text colour of "Our Top Pics" is still the same. Fix that if possible

**Comment by Goose-Of-War** [comment]
![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/a1fba043-0f09-425a-89a2-d007fda81476)
The same for the arrow for the list. Changing the colour of that would make it better

**Comment by VikasRavidas** [comment]
Please check the commits made.

**Comment by Goose-Of-War** [comment]
Looks good
