### ISSUE TITLE
Responsiveness issues

### ISSUE THREAD

**Issue by Goose-Of-War** [Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070#5]
![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/2c8f54a0-8ff3-4c03-b612-23b8090e8664)
![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/7306a3be-3de3-46ad-ae3c-9a1b108a73d3)

**Comment by VikasRavidas** [comment]
But how can I check that one .

**Comment by Goose-Of-War** [comment]
You can go to Inspect Element and click on the icon which is Blue
![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/d6b2e657-b34f-45a0-9dda-f9e7fce4e0ea)

**Comment by VikasRavidas** [comment]
Please check once and let me know the issues.

**Comment by Goose-Of-War** [comment]
![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/e0077201-5111-4caa-af17-ce5f985dab0c)
![image](https://github.com/Vikas123eng/MASK-W23-Vikas-Ravidas-22MA10070/assets/64352864/1be547ad-f0ec-436c-9b42-5936c699fef3)

The icon bar on the left, how do you want to proceed with them, because in both cases, they look weird

**Comment by VikasRavidas** [comment]
Sorry, working on them.

**Comment by Goose-Of-War** [comment]
Nothing to be sorry about. You're learning in this task round. It's all normal.

**Comment by VikasRavidas** [comment]
Any tips to make it compatible with smart phones?

**Comment by Goose-Of-War** [comment]
Um... Right. Sorry, was a bit busy. Will tell you later in the interview rounds or something. Or you can ping me in the WhatsApp group or something. Good luck
